### ISSUE TITLE
Valid plan is not found

### ISSUE THREAD

**Issue by IreneBrugnara** [aiplan4eu/up-enhsp#18]
The attached problem solved by ENHSP returns status UNSOLVABLE_PROVEN, but a valid plan does exist.
[problem.txt](https://github.com/aiplan4eu/up-enhsp/files/14052216/problem.txt)

**Comment by hstairs** [comment]
Thanks Irene. That was indeed a bug that I have fixed and pushed a new version of enhsp. I am going to push a new version of the up-enhsp too straight away!

**Comment by IreneBrugnara** [comment]
Great, thank you!
