### ISSUE TITLE
Enhsp Test Example

### ISSUE THREAD

**Issue by Soooddi96** [aiplan4eu/up-enhsp#9]
I have tried the Enhsp planner with the robot test example that is given and the output is the following "No plan found", I have tried the Tamer and Pyperplan planners and they both give me the solution plan. It seems like Enhsp was working during the ICAPS 2022 demo but it is no longer the case. Can I have more information about this issue ? 

Best,

**Comment by hstairs** [comment]
Hello! Can you post here the example? There has probably been some change in the UP or something related to that. This was not expected though.

**Comment by hstairs** [comment]
Hi, I have tried the problem myself and it works with ENHSP. I only did pip3 install --pre unified_planning[enhsp], and the same works with pip3 install unified_planning[enhsp]. Perhaps try a fresh installation?
Below the python code; perhaps there is something different, but I don't think so. 

`import unified_planning as up
from unified_planning.shortcuts import *


Location = UserType('Location')
robot_at = Fluent('robot_at', BoolType(), l=Location)
connected = Fluent('connected', BoolType(), l1= Location, l2= Location)
move = InstantaneousAction('move', l_from=Location, l_to=Location)
l_from = move.parameter('l_from')
l_to = move.parameter('l_to')
move.add_precondition(connected(l_from, l_to))
move.add_precondition(robot_at(l_from))
move.add_effect(robot_at(l_from), False)
move.add_effect(robot_at(l_to), True)

problem = Problem('robot')
problem.add_fluent(robot_at, default_initial_value=False)
problem.add_fluent(connected, default_initial_value=False)
problem.add_action(move)

NLOC = 10
locations = [unified_planning.model.Object('l%s' % i, Location) for i in range(NLOC)]
problem.add_objects(locations)

problem.set_initial_value(robot_at(locations[0]), True)
for i in range(NLOC - 1):
    problem.set_initial_value(connected(locations[i], locations[i + 1]), True)

problem.add_goal(robot_at(locations[-1]))

with OneshotPlanner(name='enhsp') as planner:
    result = planner.solve(problem)
    if (result.status == up.engines.PlanGenerationResultStatus.SOLVED_SATISFICING):
        plan = result.plan    
        print(plan)
    else:
        print("no plan")
`

**Comment by Soooddi96** [comment]
Hi, thank you for the reply, I managed to solve it
